// Comments generated by ChatGPT for learning purposes.
module.exports = {
  // The setupFilesAfterEnv option allows you to provide a list of modules that run some code to configure or set up the testing environment before each test suite
  setupFilesAfterEnv: ["./setupAfterEnv.ts"],
  // Force Jest to exit after all tests have completed running
  forceExit: true,

  // Specify a global teardown module that will run after all test suites
  globalTeardown: "./src/tests/teardown.ts",

  // Patterns to locate test files
  testMatch: ["**/tests/**/*.test.ts"],

  // Set the maximum time allowed for each test to complete
  testTimeout: 30000,

  // Use "ts-jest" preset to handle TypeScript files
  preset: "ts-jest",

  // Specify the test environment, "node" is used for Node.js environments
  testEnvironment: "node",

  // Display individual test results with the test suite hierarchy
  verbose: true,

  // Automatically clear mock calls and instances between every test
  clearMocks: true,

  // Extensions of modules to be used in tests
  moduleFileExtensions: ["ts", "js"],

  // A map from regular expressions to paths to transformers
  transform: {
    "^.+\\.ts$": "ts-jest", // Use "ts-jest" to transform TypeScript files
  },

  transform: {
    "^.+\\.tsx?$": ["ts-jest", { tsconfig: "tsconfig.json" }],
  },

  // Enable collecting code coverage information
  collectCoverage: true,

  // Specify the patterns to include or exclude files from coverage collection
  collectCoverageFrom: [
    "src/**/*.{ts,js}", // Include all TypeScript and JavaScript files in "src" directory
    "!src/**/*.d.ts", // Exclude TypeScript declaration files
    "!**/*.test.ts", // Exclude test files
    "!**/*.spec.ts", // Exclude spec files
    "!**/node_modules/**", // Exclude files in "node_modules" directory
    "!**/.eslintrc.js", // Exclude ESLint configuration files
    "!**/index.ts", // Exclude "index.ts" files
    "!**/logger.ts", // Exclude "logger.ts" files
    "!**/middleware.ts", // Exclude "middleware.ts" files
    "!**/app.ts", // Exclude "app.ts" files
  ],

  // Reporters to use for displaying coverage information
  coverageReporters: ["text", "html"], // Generate coverage reports in text and HTML format

  // Ignore specific paths from coverage collection (i.e the older blog API test file)
  modulePathIgnorePatterns: [
    "<rootDir>/dist/",
    "<rootDir>/src/tests/utils/list_helper.test.ts",
    "<rootDir>/src/tests/utils/user_api.test.ts", // Ignore user API test file. I have doine this because I am getting conflicting test results. I need a deeper spike into Supertest.
  ],
};
